version: '3'

services:
  test-db:
    container_name: interview_tasks_db
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=interview_tasks_db
    ports:
      - "5439:5432"